swagger: "2.0"
info:
  description: "Essa API é responsável pela geração de chamados"
  version: "1.0"
  title: "Teste Eng Software Publico"
host: "teste-eng-api.herokuapp.com"
basePath: "/am-day"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths: 
  /am-day:
    get:
      tags:
        - "Chamados"
      summary: "Recebe os chamados atribuidos aos trabalhadores"
      description: "Recebe os chamados atribuidos aos trabalhadores"
      operationId: "getChamados"
      produces:
        - "application/json"
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/ChamadoComTrabalhadorAtribuidoDTO"
definitions:
  ChamadoComTrabalhadorAtribuidoDTO:
    type: 'object'
    properties:
      id:
        type: 'string'
        example: '13'
      dataDeAbertura:
        type: 'string'
      nome: 
        type: 'string'
        example: 2022-05-05
